### ISSUE TITLE
Console Error: Failed to parse SourceMap: http://localhost:8080/angular-photoswipe.min.js.map

### ISSUE THREAD

**Issue by Danlowe95** [Danlowe95/IBEIS-web#12]
90% sure photoswipe is not used anymore, it can most likely be removed entirely.  Check to make sure it is unused first (or remove it and do testing to see if anything breaks).  

Photoswipe documentation: http://photoswipe.com/

**Comment by lee0c** [comment]
I've checked and it doesn't seem to be used at all. Removing it causes no errors as far as I'm seeing
