### ISSUE TITLE
detection review does not load correctly on first load. 

### ISSUE THREAD

**Issue by Danlowe95** [Danlowe95/IBEIS-web#14]
You need to click "get next" in order for it to start.   I have tried debugging this and can't figure out why this happens, as the same method is called each time.  It may have to do with the dialog not being opened at the beginning when the first call is made.

**Comment by brennn-rpi** [comment]
The issue was that the dialog tried to display the HTML form before the form itself was ready on the Wildbook server side. I added some steps to serialize the calls, and it should work as expected now.
