### ISSUE TITLE
Workspace name CSS needs resizing/cutting

### ISSUE THREAD

**Issue by Danlowe95** [Danlowe95/IBEIS-web#6]
side bar and top bar, fit space

**Comment by alabgold** [comment]
Can you elaborate on this problem?

**Comment by Danlowe95** [comment]
This is a really simple bug.  If the workspace name is very long, the text in the left-bar displaying it will cut off instead of resizing (html is workspace-left.html).  I'm not sure the "proper" html fix, but I assume some form of logic that says "shrink font size so that the text doesn't overflow out of the div" is all you need.
