### ISSUE TITLE
Map does not work

### ISSUE THREAD

**Issue by Danlowe95** [Danlowe95/IBEIS-web#7]

**Comment by Danlowe95** [comment]
getting the map working again.  This uses leaflet.js I believe (or was planned to).  It was working but we were getting some issues where it required a screen resize to work.  Now something somewhere broke.  Map implementation in the future will add "pins" at all picture locations in the workspace with GPS data.  For now, just have the map load when the user clicks that tab.

**Comment by brennn-rpi** [comment]
#19 Leaflet map added, resize issue _should_ be taken care of (I can no longer reproduce it consistently), markers are placed for each image with available location data.
